project_id = "odqxxyuqvjhdxrmdeaer"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.refresh-transactions]
verify_jwt = false
[edge_functions.refresh-payment]
verify_jwt = false