// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://odqxxyuqvjhdxrmdeaer.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcXh4eXVxdmpoZHhybWRlYWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxNDQ5NDAsImV4cCI6MjA0NzcyMDk0MH0.TqL9zbo9i4FkP37gJLvO_3notTs6rYg_WCVZhbZvOeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);